name: Profile stats

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
      - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.USER_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Europe/Prague
          repositories_forks: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_habits: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          
          plugin_licenses: yes
          plugin_languages_skipped: conan-center-index, oh-my-zsh
          plugin_isocalendar: yes
